apiVersion: v1
kind: Service
metadata:
  name: nestjs-cloud-setup
spec:
  selector:
    app: nestjs-cloud-setup
  type: LoadBalancer 
  ports:
    - protocol: TCP
      port: 3010
      targetPort: 3010
      nodePort: 31010